name: Deploy to Netlify

on:
  push:
    branches:
      - main  # Déclenche le déploiement à chaque push sur main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install  # ou autre gestionnaire de packages

      - name: Build project
        run: npm run build  # Adapter selon le projet

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: "./dist"  # Adapter selon le dossier de build (ex: build, out, etc.)
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Auto-deploy via GitHub Actions"
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
